### ISSUE TITLE
Questions about data

### ISSUE THREAD

**Issue by Zongliang-Wu** [sunwei925/RQ-VQA#1]
Awesome work!

I have some questions below:

### Test data ground truth
 I notice the ablation study in the paper is using test data instead of val data. But I find that the ground truth of test data is not available. Maybe it is my problem that I did not find them. Can you please provide the URL of test data ground truth?

### Bug 
I guess the `test.py ` has a mistake `model = baseline_Swin_motion.Swin_b_384_in22k_SlowFast_Fast_LLM_LIQE_FASTVQA_BoT(None)` should be `model = models.RQ_VQA(None)`. Is it correct?

### Output Score
 Follow the readme, I run the test script using the features and checkpoints  provided in your googledrive. But there are many Negative Numbers in the output score which different from the submission example `predict.csv `. Can you help me to figure out where my mistakes?

Here are some examples：
my output:
 <html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

filename | score
-- | --
test/0001.mp4 | -2.677163303
test/0002.mp4 | -1.875817172
test/0003.mp4 | -1.983064221
test/0004.mp4 | -2.511469623
test/0005.mp4 | -2.639196724
test/0006.mp4 | -3.618618083
test/0007.mp4 | -4.521251822
test/0008.mp4 | -2.464179084
test/0009.mp4 | -1.859043884
test/0010.mp4 | -1.846062425

</body>

</html>

In 'predict.csv`
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

filename | score
-- | --
test/0001.mp4 | 0.016778059
test/0002.mp4 | 0.588705462
test/0003.mp4 | 4.771529994
test/0004.mp4 | 4.813955309
test/0005.mp4 | 1.838624071
test/0006.mp4 | 2.46454457
test/0007.mp4 | 0.169009474
test/0008.mp4 | 3.313553744
test/0009.mp4 | 4.916614912
test/0010.mp4 | 0.570947946

</body>

</html>

**Comment by sunwei925** [comment]
Thanks for pointing out the mistake. I will fix it. Regarding the question, since we only use PLCC loss to optimize the model, the trained model will aim to achieve a high PLCC value between the model outputs and the ground-truth scores. This approach does not ensure that individual video scores will closely match their respective ground-truth values. To make the model scores more understandable, you can use the four-parameter logistic fitting function [y_output_logistic = fit_function(y_label, y_output) in util.py] to map the model scores to the scale of the ground-truth scores.

**Comment by Zongliang-Wu** [comment]
Many thanks for your detailed reply!!!
